source "https://rubygems.org"

gem "minima"
gem "jekyll", "~> 4.3"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-sitemap"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-feed"
  gem "jekyll-sitemap"
end
